_wandb:
    value:
        cli_version: 0.24.0
        e:
            l52uym2f9omk632qm1ut7bg9gr06whic:
                args:
                    - -s
                    - -vv
                    - .
                    - --reference_artifact
                    - exercise_14/preprocessed_data.csv:latest
                    - --sample_artifact
                    - preprocessed_data.csv:latest
                    - --ks_alpha
                    - "0.05"
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "2160158191616"
                        used: "623067291648"
                email: ecarro11@wgu.edu
                executable: /home/student/.conda/envs/mlflow-cd65784bf8e7fffc45c3ae66d3b5f5d3b28be86d/bin/python3.13
                git:
                    commit: a1a499e11bbdfeb11edf79b9ded8112d29c27988
                    remote: https://github.com/elsiedcarroll/genre_classification.git
                host: 3899575616c73ef7684b0fb72c7f3450c25f5740-744c786b9c-m6njt
                memory:
                    total: "135077654528"
                os: Linux-6.6.97+-x86_64-with-glibc2.36
                program: /home/student/.conda/envs/mlflow-cd65784bf8e7fffc45c3ae66d3b5f5d3b28be86d/bin/pytest
                python: CPython 3.13.14
                root: /workspace/genre_classification/check_data
                startedAt: "2026-06-25T00:28:51.061538Z"
                writerId: l52uym2f9omk632qm1ut7bg9gr06whic
        m: []
        python_version: 3.13.14
        t:
            "4": 3.13.14
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
